### ISSUE TITLE
No Device Detected

### ISSUE THREAD

**Issue by HarakiriTiger** [JennoVink/MidiKeyboardSoundboard#16] opened 2022-09-27 01:24 UTC
Hi, like a previous poster, I too cant attach any buttons in the 1.0 release as well as the "for nino" one.
In the third most recent one, I dont even see my Xone:4D in the first place. 
Turning the autosensing-support on doesnt help in either of the two releases.
Using MidiView I can see a constant stream of F8 on Channel 0 coming from my Xone, so it seems like it still doesnt ignore my autosense stream. 
When I am fast enough, I can get it to eat the actual button I press inbetween the F8s, but it wont play any sound.

Its possible the latest release has it fixed, but first I´d need to see my device there. 
Pressing F8 wont do anything either, so I dont really know what else to try.

Thanks in advance!

**Comment by JennoVink** [comment] 2022-09-28 12:37
@HarakiriTiger thanks for raising this issue. When I have time, I'll check if there's a bug in the autosensing mechanism. Note that the f8 key is reserved for debug logging... 🙃 Maybe I'll choose another key for that in the future.

**Comment by JennoVink** [comment] 2022-10-22 19:57
@HarakiriTiger I found time to fix the autosensing mechanism. This was indeed hardcoded. I made this dynamic now :) 

Please checkout the v1.3 release [here](https://github.com/JennoVink/MidiKeyboardSoundboard/releases/tag/v1.3).

**Comment by JennoVink** [comment] 2022-10-22 19:58
Please let me know what your experiences are with this new release.

**Comment by HarakiriTiger** [comment] 2022-10-23 21:49
@JennoVink Hey, glad you found time to look for a fix! Unfortunately I can only download the source code and dont know how to make it work with just that. Please add an executable release too so I can give it a go.
Thank you very much!

**Comment by JennoVink** [comment] 2022-10-24 10:20
@HarakiriTiger Thanks for your reply and patience. I added a .7z file. Please extract that and start MidiKeyboardSoundboard.exe. Let me know if this one works for you!

**Comment by HarakiriTiger** [comment] 2022-10-24 11:00
@JennoVink Thanks for uploading the 7zip! Unfortunately it still doesnt detect my device. I am seeing the MIDI triggers with a readout program, so the connection to my PC seems to be working. 
I could select the xone:4D in your 1.0 and the "for nino" release, so I guess something you changed after that brings up this issue.
Let me know if I can test anything for you or you need some more info! Wish I knew more....

**Comment by JennoVink** [comment] 2022-10-25 17:37
Update: based on a [quick technical comparison between the two versions](https://github.com/JennoVink/MidiKeyboardSoundboard/compare/v1.1-alpha...v1.3) , I couldn't see a bug. Soon, I'll create a small debug application to check which midi devices it can find. Hopefully, that will give more information to me. It works on my machine, that's what makes this problem a bit harder to fix.

**Comment by JennoVink** [comment] 2022-10-28 17:15
Please checkout the following file: [MidiDeviceMonitor.zip](https://github.com/JennoVink/MidiKeyboardSoundboard/files/9890553/Release.zip). I created a debug application which lists the connected midi devices, and the events. Please send me a screenshot when you ran the software :). Using mail is also fine by me:  soundboard@jennovink.nl.

**Comment by TelepathicRyuu** [comment] 2023-02-03 01:41
I have the same issue as the post author I think. I used the MidiDeviceMonitor and it showed my Akai mpk mini, but launching the application itself doesn't detect the midi device, F8 doesn't do anything, I cannot bind the keys. Oddly enough, I tried the initial release version and it detects my midi device, but it does not play anything, even though it registers keys and the sound sample. I do have a VoiceMeeter setup, and I tried the suggested approach in how to make it work, so I am pretty sure that wasn't the problem.

**Comment by JennoVink** [comment] 2023-02-03 17:53
Thank you for your message. I'm pretty sure I introduced this behavior when optimizing the code. Although it did work on my machine all the time.

When I have some spare time, I'll have a look into it. It's good to know that the midi device monitor debug application worked.

Kind regards,
Jenno

________________________________

**Comment by TelepathicRyuu** [comment] 2023-02-04 18:08
I greatly appreciate the software and your work! I actually managed to get the initial release version to work. It was the only version that recognized the midi controller as I mentioned earlier. Although it doesn't work with launchpad type buttons, it works with piano type keys, so it is still somewhat functional, the knob controllers do not work either. Just thought that maybe this information will be somewhat useful, for now, even though janky, it works and it does wonders for how simple it is! I am excited to see the latest release working!

**Comment by JennoVink** [comment] 2023-02-07 21:30
@HarakiriTiger @TelepathicRyuu I drafted a new release. Please checkout [the release page](https://github.com/JennoVink/MidiKeyboardSoundboard/releases/tag/v1.4 ). Let me know if this works!

**Comment by TelepathicRyuu** [comment] 2023-02-07 21:46
Greetings! It works! It detects my midi, I can use all the functions and the volume controller now works as intended. There is one interesting issue though. When I try to play sound samples using launchpad type buttons it works, but when I try to assign the launchpad type button to stop sounds, it does not work(I checked with your device monitor and my own device monitor software, they both detect the button and assigned values to that button correctly). However, when I assign standard piano type key as a stop button, it works. Aside from this one thing, everything else is great, I tested all of the other functions just in case as well, holding to continue to play sound works as well as looping!

**Comment by JennoVink** [comment] 2023-02-07 22:05
Good to hear that it works good! When I have some spare time I'll have a look into the 'stop button' problem.
Kind regards,
Jenno

Met vriendelijke groeten,

Jenno
________________________________

**Comment by TelepathicRyuu** [comment] 2023-02-07 23:43
Something that I noticed with file names that are longer than one line is that the remove button gets moved so far down you cant actually remove it (This can be fixed by changing the file to a file name that is smaller).

![image](https://user-images.githubusercontent.com/23217454/217392190-596b0030-cc73-4b53-bf98-71b5320e7a3b.png)

I am new to github, so I apologize if I need to make a brand new issue on this, I can do that as well!

**Comment by JennoVink** [comment] 2023-02-08 07:43
@TelepathicRyuu That's quite funny. At the time of writing I tried with longer names and thought "users won't get any longer filenames than this", but you prove otherwise haha ;). Feel free to create an issue for each problem you're having. (one for the mp3 name that pushes the delete button down, one for the stop button that only can be assigned to piano keys).

**Closed as completed by JennoVink** 2023-02-08 07:43 UTC
